<?php

namespace App\Console\Commands;

use Illuminate\Console\Command;
use App\Models\PrepaidRentTransaction;
use Carbon\Carbon;
use Illuminate\Support\Facades\Log;

class PrepaidRentAmortizeCommand extends Command
{
    /**
     * The name and signature of the console command.
     *
     * @var string
     */
    protected $signature = 'prepaid-rent:amortize {--date= : Override current date (Y-m-d) for backfill/testing}';

    /**
     * The console command description.
     *
     * @var string
     */
    protected $description = 'Generate amortization schedules and post monthly prepaid rent amortization automatically';

    /**
     * Execute the console command.
     */
    public function handle(): int
    {
        $now = $this->option('date') ? Carbon::parse($this->option('date')) : now();
        $period = $now->copy()->startOfMonth();
        $this->info("Running prepaid rent amortization for period {$period->format('Y-m')}");

        $topups = PrepaidRentTransaction::with('schedules')
            ->where('transaction_type', 'topup')
            ->where(function ($query) {
                $query->whereNotNull('amortization_months')
                    ->orWhere(function ($inner) {
                        $inner->whereNotNull('rental_start_date')
                            ->whereNotNull('rental_end_date');
                    });
            })
            ->get();

        $processed = 0;
        foreach ($topups as $topup) {
            $schedules = $topup->ensureSchedules();

            foreach ($schedules as $schedule) {
                $schedulePeriod = Carbon::create($schedule->period_year, $schedule->period_month, 1)->startOfMonth();
                if ($schedulePeriod->gt($period)) {
                    continue; // future schedules
                }

                if ($schedule->posted_at || $schedule->amortization_transaction_id) {
                    continue; // already posted
                }

                $amortizationDate = $schedulePeriod->copy()->endOfMonth();
                if ($topup->rental_end_date) {
                    $endDate = Carbon::parse($topup->rental_end_date)->endOfDay();
                    if ($amortizationDate->gt($endDate)) {
                        $amortizationDate = $endDate->toDateString();
                    }
                }

                $amortization = PrepaidRentTransaction::create([
                    'transaction_date' => $amortizationDate,
                    'transaction_type' => 'amortization',
                    'amount' => $schedule->amount,
                    'description' => "Auto amortization prepaid rent {$schedulePeriod->format('M Y')} (Top-up #{$topup->id})",
                    'source_type' => 'other',
                    'notes' => 'Generated by prepaid-rent:amortize',
                    'created_by' => null,
                ]);

                $schedule->update([
                    'amortization_transaction_id' => $amortization->id,
                    'posted_at' => now(),
                ]);

                $processed++;
            }
        }

        $this->info("Amortization posting completed. Entries created: {$processed}");
        Log::info('prepaid-rent:amortize executed', [
            'period' => $period->format('Y-m'),
            'created' => $processed,
        ]);

        return Command::SUCCESS;
    }
}
