<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Carbon\Carbon;

class PettyCashTransaction extends Model
{
    use HasFactory;

    protected $fillable = [
        'transaction_date',
        'description',
        'category_id',
        'template_id',
        'categorization_method',
        'auto_generated',
        'invoice_id',
        'invoice_item_id',
        'amount',
        'type',
        'so_number',
        'balance_after',
        'notes',
        'receipt_file',
        'status',
        'user_id',
        'approved_by',
        'approved_at',
    ];

    protected $casts = [
        'transaction_date' => 'date',
        'amount' => 'decimal:2',
        'balance_after' => 'decimal:2',
        'approved_at' => 'datetime',
        'auto_generated' => 'boolean',
    ];

    public function category()
    {
        return $this->belongsTo(PettyCashCategory::class, 'category_id');
    }

    public function user()
    {
        return $this->belongsTo(User::class);
    }

    public function approver()
    {
        return $this->belongsTo(User::class, 'approved_by');
    }

    public function template()
    {
        return $this->belongsTo(ExpenseTemplate::class, 'template_id');
    }

    public function invoice()
    {
        return $this->belongsTo(Invoice::class, 'invoice_id');
    }

    public function invoiceItem()
    {
        return $this->belongsTo(InvoiceItem::class, 'invoice_item_id');
    }

    public function scopeByType($query, $type)
    {
        return $query->where('type', $type);
    }

    public function scopeByStatus($query, $status)
    {
        return $query->where('status', $status);
    }

    public function scopeByDateRange($query, $startDate, $endDate)
    {
        return $query->whereBetween('transaction_date', [$startDate, $endDate]);
    }

    public function scopeToday($query)
    {
        return $query->whereDate('transaction_date', Carbon::today());
    }

    public function scopeThisMonth($query)
    {
        return $query->whereMonth('transaction_date', Carbon::now()->month)
                    ->whereYear('transaction_date', Carbon::now()->year);
    }

    public function getFormattedAmountAttribute()
    {
        return 'Rp ' . number_format($this->amount, 0, ',', '.');
    }

    public function getFormattedBalanceAfterAttribute()
    {
        return 'Rp ' . number_format($this->balance_after, 0, ',', '.');
    }

    public function isExpense()
    {
        return $this->type === 'expense';
    }

    public function isTopup()
    {
        return $this->type === 'topup';
    }

    public function isRefund()
    {
        return $this->type === 'refund';
    }

    // New scopes for template integration
    public function scopeAutoGenerated($query)
    {
        return $query->where('auto_generated', true);
    }

    public function scopeManual($query)
    {
        return $query->where('auto_generated', false);
    }

    public function scopeByCategorizationMethod($query, $method)
    {
        return $query->where('categorization_method', $method);
    }

    public function scopeFromInvoice($query, $invoiceId)
    {
        return $query->where('invoice_id', $invoiceId);
    }

    // Helper methods
    public function isAutoGenerated()
    {
        return $this->auto_generated;
    }

    public function getCategorizationMethodTextAttribute()
    {
        return match($this->categorization_method) {
            'template' => 'Template',
            'keyword' => 'Keyword Match',
            'manual' => 'Manual Selection',
            default => 'Unknown'
        };
    }
}
